version: 2
updates:
  - package-ecosystem: "pip" 
    directory: "/" 
    schedule:
      interval: "daily"
      time: "12:30"
    reviewers:
     - "Pandademic"
     labels:
      - "Documentation"

    
