Name: "Data Viewer"
Current version: 
       - 0.01
       - "Test"
Created by: "Pandademic and Smurfy Durfy"
Github URL : "https://github.com/Pandademic/DataViewer"
License: "GNU 3.0"
Finished: "False"
DEVELOP: True

