Name: "Data Viewer"
Liscence: "GNU public 3"
version: 0.01
Nightly: True
Github: True
Stable:  False
Enabled: False
Theme : "Default"
Warnings:
  - "1:This is unstable"
key: "PotatoBannanaAppleXD"
Finished: "False"
DEV: True
