name: Automatic Releases


on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - name: "RELEASE"
       uses: marvinpinto/action-automatic-releases@v1.2.1
       with:     
              repo_token: ${{ secrets.GITHUB_TOKEN }}
    # Release title (for automatic releases)
              title: "Nightly Dev Build[UNSTABLE]"
              automatic_release_tag: "Indev"

